export const skipElements = {
  APPLET: true,
  AREA: true,
  BASE: true,
  FRAME: true,
  FRAMESET: true,
  HR: true,
  IFRAME: false,
  IMG: true,
  INPUT: true,
  LINK: true,
  META: true,
  MAP: true,
  NOSCRIPT: true,
  OBJECT: true,
  PARAM: true,
  SCRIPT: true,
  STYLE: true,
  TEXTAREA: true,
  EMBED: true,
  VIDEO: false,
  AUDIO: true,
  SOURCE: true,
  TRACK: true,
  CANVAS: true,
  SVG: true,
  MATH: true
}
